name: Publish Node package

on:
  workflow_call:
    inputs:
      node-version:
        type: string
        required: false
        default: '20'
      registry-url:
        type: string
        required: false
        default: 'https://registry.npmjs.org'
      needs-build:
        type: boolean
        required: false
        default: true
      build-script:
        type: string
        required: false
        default: 'build'
      package-version:
        type: string
        required: false
    secrets:
      node-auth-token:
        required: true

jobs:
  publish-node-package:
    name: Publish Node package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ inputs.node-version }}
          registry-url: ${{ inputs.registry-url }}

      - name: Install dependencies
        if: ${{ inputs.needs-build }}
        run: npm clean-install

      - name: Build package
        if: ${{ inputs.needs-build }}
        run: npm run-script ${{ inputs.build-script }}

      - name: Set package version
        if: ${{ inputs.package-version }}
        run: npm version --no-git-tag-version ${{ inputs.package-version }}

      - name: Publish package
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.node-auth-token }}
