name: Test Node project

on:
  workflow_call:
    inputs:
      node-version:
        type: string
        required: false
        default: '20'
      test-script:
        type: string
        required: false
        default: 'test:coverage'
      upload-coverage:
        type: boolean
        required: false
        default: false
      coverage-files:
        type: string
        required: false
        default: './coverage/coverage-final.json'
    secrets:
      codecov-token:
        required: false

jobs:
  test-node-project:
    name: Test Node project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ inputs.node-version }}

      - name: Install dependencies
        run: npm clean-install

      - name: Run tests
        run: npm run-script ${{ inputs.test-script }}

      - name: Upload coverage
        if: ${{ inputs.upload-coverage }}
        uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.codecov-token }}
        with:
          files: ${{ inputs.coverage-files }}
