name: Test simple project

on:
  workflow_call:
    inputs:
      node-version:
        type: string
        required: false
        default: '18'
      test-script:
        type: string
        required: false
        default: 'test:coverage'
      upload-code-coverage:
        type: boolean
        required: false
        default: false
      code-coverage-files:
        type: string
        required: false
        default: './coverage/coverage-final.json'

jobs:
  test-simple-project:
    name: Test simple project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}

      - name: Install dependencies
        run: npm clean-install

      - name: Run tests
        run: npm run-script ${{ inputs.test-script }}

      - name: Upload code coverage
        if: ${{ inputs.upload-code-coverage }}
        uses: codecov/codecov-action@v3
        with:
          files: ${{ inputs.code-coverage-files }}
